version: "3.8"
services:
  app:
    container_name: spike_model
    build: .
    command: python main.py
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app